spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: sys1
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # veya update / none / create-drop (dev için)
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

app:
  security:
    jwt:
      secret: "C/gzRSoxa/wWapxWGKVG9TBrlxSCjTlVVH3ZUhUuwGuzKZ0aoI7SHYq6upqURoTE04KV4N9tH4ZrTYqKgeIdHQ=="

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html